#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.2.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

use crate::config::SMTCConfig;
use crate::metadata::MusicMetadata;
use crate::timeline::PlaybackTimeline;

// Section: wire functions

fn wire_initialize_media_player_impl(
    port_: MessagePort,
    config: impl Wire2Api<SMTCConfig> + UnwindSafe,
    timeline: impl Wire2Api<PlaybackTimeline> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "initialize_media_player",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_config = config.wire2api();
            let api_timeline = timeline.wire2api();
            move |task_callback| initialize_media_player(api_config, api_timeline)
        },
    )
}
fn wire_update_config_impl(port_: MessagePort, config: impl Wire2Api<SMTCConfig> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_config",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_config = config.wire2api();
            move |task_callback| update_config(api_config)
        },
    )
}
fn wire_update_metadata_impl(
    port_: MessagePort,
    metadata: impl Wire2Api<MusicMetadata> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_metadata",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_metadata = metadata.wire2api();
            move |task_callback| update_metadata(api_metadata)
        },
    )
}
fn wire_update_timeline_impl(
    port_: MessagePort,
    timeline: impl Wire2Api<PlaybackTimeline> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_timeline",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_timeline = timeline.wire2api();
            move |task_callback| update_timeline(api_timeline)
        },
    )
}
fn wire_update_playback_status_impl(
    port_: MessagePort,
    status: impl Wire2Api<PlaybackStatus> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_playback_status",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_status = status.wire2api();
            move |task_callback| update_playback_status(api_status)
        },
    )
}
fn wire_disable_smtc_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "disable_smtc",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| disable_smtc(),
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}

impl Wire2Api<i32> for i32 {
    fn wire2api(self) -> i32 {
        self
    }
}
impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}

impl Wire2Api<PlaybackStatus> for i32 {
    fn wire2api(self) -> PlaybackStatus {
        match self {
            0 => PlaybackStatus::Closed,
            1 => PlaybackStatus::Changing,
            2 => PlaybackStatus::Stopped,
            3 => PlaybackStatus::Playing,
            4 => PlaybackStatus::Paused,
            _ => unreachable!("Invalid variant for PlaybackStatus: {}", self),
        }
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_initialize_media_player(port_: MessagePort, config: JsValue, timeline: JsValue) {
        wire_initialize_media_player_impl(port_, config, timeline)
    }

    #[wasm_bindgen]
    pub fn wire_update_config(port_: MessagePort, config: JsValue) {
        wire_update_config_impl(port_, config)
    }

    #[wasm_bindgen]
    pub fn wire_update_metadata(port_: MessagePort, metadata: JsValue) {
        wire_update_metadata_impl(port_, metadata)
    }

    #[wasm_bindgen]
    pub fn wire_update_timeline(port_: MessagePort, timeline: JsValue) {
        wire_update_timeline_impl(port_, timeline)
    }

    #[wasm_bindgen]
    pub fn wire_update_playback_status(port_: MessagePort, status: i32) {
        wire_update_playback_status_impl(port_, status)
    }

    #[wasm_bindgen]
    pub fn wire_disable_smtc(port_: MessagePort) {
        wire_disable_smtc_impl(port_)
    }

    // Section: allocate functions

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }

    impl Wire2Api<MusicMetadata> for JsValue {
        fn wire2api(self) -> MusicMetadata {
            let self_ = self.dyn_into::<JsArray>().unwrap();
            assert_eq!(
                self_.length(),
                6,
                "Expected 6 elements, got {}",
                self_.length()
            );
            MusicMetadata {
                title: self_.get(0).wire2api(),
                artist: self_.get(1).wire2api(),
                album: self_.get(2).wire2api(),
                album_artist: self_.get(3).wire2api(),
                track_number: self_.get(4).wire2api(),
                thumbnail: self_.get(5).wire2api(),
            }
        }
    }
    impl Wire2Api<Option<String>> for Option<String> {
        fn wire2api(self) -> Option<String> {
            self.map(Wire2Api::wire2api)
        }
    }

    impl Wire2Api<PlaybackTimeline> for JsValue {
        fn wire2api(self) -> PlaybackTimeline {
            let self_ = self.dyn_into::<JsArray>().unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            PlaybackTimeline {
                start_time_ms: self_.get(0).wire2api(),
                end_time_ms: self_.get(1).wire2api(),
                position_ms: self_.get(2).wire2api(),
                min_seek_time_ms: self_.get(3).wire2api(),
                max_seek_time_ms: self_.get(4).wire2api(),
            }
        }
    }
    impl Wire2Api<SMTCConfig> for JsValue {
        fn wire2api(self) -> SMTCConfig {
            let self_ = self.dyn_into::<JsArray>().unwrap();
            assert_eq!(
                self_.length(),
                7,
                "Expected 7 elements, got {}",
                self_.length()
            );
            SMTCConfig {
                play_enabled: self_.get(0).wire2api(),
                pause_enabled: self_.get(1).wire2api(),
                stop_enabled: self_.get(2).wire2api(),
                next_enabled: self_.get(3).wire2api(),
                prev_enabled: self_.get(4).wire2api(),
                fast_forward_enabled: self_.get(5).wire2api(),
                rewind_enabled: self_.get(6).wire2api(),
            }
        }
    }

    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<bool> for JsValue {
        fn wire2api(self) -> bool {
            self.is_truthy()
        }
    }
    impl Wire2Api<i32> for JsValue {
        fn wire2api(self) -> i32 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<i64> for JsValue {
        fn wire2api(self) -> i64 {
            ::std::convert::TryInto::try_into(self.dyn_into::<js_sys::BigInt>().unwrap()).unwrap()
        }
    }
    impl Wire2Api<Option<String>> for JsValue {
        fn wire2api(self) -> Option<String> {
            (!self.is_undefined() && !self.is_null()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<Option<i64>> for JsValue {
        fn wire2api(self) -> Option<i64> {
            (!self.is_undefined() && !self.is_null()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<PlaybackStatus> for JsValue {
        fn wire2api(self) -> PlaybackStatus {
            (self.unchecked_into_f64() as i32).wire2api()
        }
    }
    impl Wire2Api<u32> for JsValue {
        fn wire2api(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_initialize_media_player(
        port_: i64,
        config: *mut wire_SMTCConfig,
        timeline: *mut wire_PlaybackTimeline,
    ) {
        wire_initialize_media_player_impl(port_, config, timeline)
    }

    #[no_mangle]
    pub extern "C" fn wire_update_config(port_: i64, config: *mut wire_SMTCConfig) {
        wire_update_config_impl(port_, config)
    }

    #[no_mangle]
    pub extern "C" fn wire_update_metadata(port_: i64, metadata: *mut wire_MusicMetadata) {
        wire_update_metadata_impl(port_, metadata)
    }

    #[no_mangle]
    pub extern "C" fn wire_update_timeline(port_: i64, timeline: *mut wire_PlaybackTimeline) {
        wire_update_timeline_impl(port_, timeline)
    }

    #[no_mangle]
    pub extern "C" fn wire_update_playback_status(port_: i64, status: i32) {
        wire_update_playback_status_impl(port_, status)
    }

    #[no_mangle]
    pub extern "C" fn wire_disable_smtc(port_: i64) {
        wire_disable_smtc_impl(port_)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_i64_0(value: i64) -> *mut i64 {
        support::new_leak_box_ptr(value)
    }

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_music_metadata_0() -> *mut wire_MusicMetadata {
        support::new_leak_box_ptr(wire_MusicMetadata::new_with_null_ptr())
    }

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_playback_timeline_0() -> *mut wire_PlaybackTimeline {
        support::new_leak_box_ptr(wire_PlaybackTimeline::new_with_null_ptr())
    }

    #[no_mangle]
    pub extern "C" fn new_box_autoadd_smtc_config_0() -> *mut wire_SMTCConfig {
        support::new_leak_box_ptr(wire_SMTCConfig::new_with_null_ptr())
    }

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_0(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }

    impl Wire2Api<i64> for *mut i64 {
        fn wire2api(self) -> i64 {
            unsafe { *support::box_from_leak_ptr(self) }
        }
    }
    impl Wire2Api<MusicMetadata> for *mut wire_MusicMetadata {
        fn wire2api(self) -> MusicMetadata {
            let wrap = unsafe { support::box_from_leak_ptr(self) };
            Wire2Api::<MusicMetadata>::wire2api(*wrap).into()
        }
    }
    impl Wire2Api<PlaybackTimeline> for *mut wire_PlaybackTimeline {
        fn wire2api(self) -> PlaybackTimeline {
            let wrap = unsafe { support::box_from_leak_ptr(self) };
            Wire2Api::<PlaybackTimeline>::wire2api(*wrap).into()
        }
    }
    impl Wire2Api<SMTCConfig> for *mut wire_SMTCConfig {
        fn wire2api(self) -> SMTCConfig {
            let wrap = unsafe { support::box_from_leak_ptr(self) };
            Wire2Api::<SMTCConfig>::wire2api(*wrap).into()
        }
    }

    impl Wire2Api<MusicMetadata> for wire_MusicMetadata {
        fn wire2api(self) -> MusicMetadata {
            MusicMetadata {
                title: self.title.wire2api(),
                artist: self.artist.wire2api(),
                album: self.album.wire2api(),
                album_artist: self.album_artist.wire2api(),
                track_number: self.track_number.wire2api(),
                thumbnail: self.thumbnail.wire2api(),
            }
        }
    }

    impl Wire2Api<PlaybackTimeline> for wire_PlaybackTimeline {
        fn wire2api(self) -> PlaybackTimeline {
            PlaybackTimeline {
                start_time_ms: self.start_time_ms.wire2api(),
                end_time_ms: self.end_time_ms.wire2api(),
                position_ms: self.position_ms.wire2api(),
                min_seek_time_ms: self.min_seek_time_ms.wire2api(),
                max_seek_time_ms: self.max_seek_time_ms.wire2api(),
            }
        }
    }
    impl Wire2Api<SMTCConfig> for wire_SMTCConfig {
        fn wire2api(self) -> SMTCConfig {
            SMTCConfig {
                play_enabled: self.play_enabled.wire2api(),
                pause_enabled: self.pause_enabled.wire2api(),
                stop_enabled: self.stop_enabled.wire2api(),
                next_enabled: self.next_enabled.wire2api(),
                prev_enabled: self.prev_enabled.wire2api(),
                fast_forward_enabled: self.fast_forward_enabled.wire2api(),
                rewind_enabled: self.rewind_enabled.wire2api(),
            }
        }
    }

    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_MusicMetadata {
        title: *mut wire_uint_8_list,
        artist: *mut wire_uint_8_list,
        album: *mut wire_uint_8_list,
        album_artist: *mut wire_uint_8_list,
        track_number: u32,
        thumbnail: *mut wire_uint_8_list,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_PlaybackTimeline {
        start_time_ms: i64,
        end_time_ms: i64,
        position_ms: i64,
        min_seek_time_ms: *mut i64,
        max_seek_time_ms: *mut i64,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_SMTCConfig {
        play_enabled: bool,
        pause_enabled: bool,
        stop_enabled: bool,
        next_enabled: bool,
        prev_enabled: bool,
        fast_forward_enabled: bool,
        rewind_enabled: bool,
    }

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    impl NewWithNullPtr for wire_MusicMetadata {
        fn new_with_null_ptr() -> Self {
            Self {
                title: core::ptr::null_mut(),
                artist: core::ptr::null_mut(),
                album: core::ptr::null_mut(),
                album_artist: core::ptr::null_mut(),
                track_number: Default::default(),
                thumbnail: core::ptr::null_mut(),
            }
        }
    }

    impl Default for wire_MusicMetadata {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    impl NewWithNullPtr for wire_PlaybackTimeline {
        fn new_with_null_ptr() -> Self {
            Self {
                start_time_ms: Default::default(),
                end_time_ms: Default::default(),
                position_ms: Default::default(),
                min_seek_time_ms: core::ptr::null_mut(),
                max_seek_time_ms: core::ptr::null_mut(),
            }
        }
    }

    impl Default for wire_PlaybackTimeline {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    impl NewWithNullPtr for wire_SMTCConfig {
        fn new_with_null_ptr() -> Self {
            Self {
                play_enabled: Default::default(),
                pause_enabled: Default::default(),
                stop_enabled: Default::default(),
                next_enabled: Default::default(),
                prev_enabled: Default::default(),
                fast_forward_enabled: Default::default(),
                rewind_enabled: Default::default(),
            }
        }
    }

    impl Default for wire_SMTCConfig {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    // Section: sync execution mode utility

    #[no_mangle]
    pub extern "C" fn free_WireSyncReturn(ptr: support::WireSyncReturn) {
        unsafe {
            let _ = support::box_from_leak_ptr(ptr);
        };
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
