// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.2.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';

abstract class SmtcWindows {
  SmtcInternal smtcNew({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcNewConstMeta;

  Future<void> smtcUpdateConfig({required SmtcInternal internal, required SMTCConfig config, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateConfigConstMeta;

  Future<void> smtcUpdateMetadata({required SmtcInternal internal, required MusicMetadata metadata, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateMetadataConstMeta;

  Future<void> smtcUpdateTimeline({required SmtcInternal internal, required PlaybackTimeline timeline, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateTimelineConstMeta;

  Future<void> smtcUpdatePlaybackStatus({required SmtcInternal internal, required PlaybackStatus status, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdatePlaybackStatusConstMeta;

  Future<void> smtcUpdateShuffle({required SmtcInternal internal, required bool shuffle, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateShuffleConstMeta;

  Future<void> smtcUpdateRepeatMode({required SmtcInternal internal, required String repeatMode, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateRepeatModeConstMeta;

  Future<void> smtcDisableSmtc({required SmtcInternal internal, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcDisableSmtcConstMeta;

  Stream<String> smtcButtonPressEvent({required SmtcInternal internal, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcButtonPressEventConstMeta;

  Stream<int> smtcPositionChangeRequestEvent({required SmtcInternal internal, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcPositionChangeRequestEventConstMeta;

  Stream<bool> smtcShuffleRequestEvent({required SmtcInternal internal, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcShuffleRequestEventConstMeta;

  Stream<String> smtcRepeatModeRequestEvent({required SmtcInternal internal, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSmtcRepeatModeRequestEventConstMeta;

  DropFnType get dropOpaqueSmtcInternal;
  ShareFnType get shareOpaqueSmtcInternal;
  OpaqueTypeFinalizer get SmtcInternalFinalizer;
}

@sealed
class SmtcInternal extends FrbOpaque {
  final SmtcWindows bridge;
  SmtcInternal.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueSmtcInternal;

  @override
  ShareFnType get shareFn => bridge.shareOpaqueSmtcInternal;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.SmtcInternalFinalizer;
}

class MusicMetadata {
  final String title;
  final String artist;
  final String album;
  final String albumArtist;
  final int trackNumber;
  final String? thumbnail;

  const MusicMetadata({
    required this.title,
    required this.artist,
    required this.album,
    required this.albumArtist,
    required this.trackNumber,
    this.thumbnail,
  });
}

enum PlaybackStatus {
  Closed,
  Changing,
  Stopped,
  Playing,
  Paused,
}

class PlaybackTimeline {
  final int startTimeMs;
  final int endTimeMs;
  final int positionMs;
  final int? minSeekTimeMs;
  final int? maxSeekTimeMs;

  const PlaybackTimeline({
    required this.startTimeMs,
    required this.endTimeMs,
    required this.positionMs,
    this.minSeekTimeMs,
    this.maxSeekTimeMs,
  });
}

class SMTCConfig {
  final bool playEnabled;
  final bool pauseEnabled;
  final bool stopEnabled;
  final bool nextEnabled;
  final bool prevEnabled;
  final bool fastForwardEnabled;
  final bool rewindEnabled;

  const SMTCConfig({
    required this.playEnabled,
    required this.pauseEnabled,
    required this.stopEnabled,
    required this.nextEnabled,
    required this.prevEnabled,
    required this.fastForwardEnabled,
    required this.rewindEnabled,
  });
}

class SmtcWindowsImpl implements SmtcWindows {
  final SmtcWindowsPlatform _platform;
  factory SmtcWindowsImpl(ExternalLibrary dylib) => SmtcWindowsImpl.raw(SmtcWindowsPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory SmtcWindowsImpl.wasm(FutureOr<WasmModule> module) => SmtcWindowsImpl(module as ExternalLibrary);
  SmtcWindowsImpl.raw(this._platform);
  SmtcInternal smtcNew({dynamic hint}) {
    return _platform.executeSync(FlutterRustBridgeSyncTask(
      callFfi: () => _platform.inner.wire_smtc_new(),
      parseSuccessData: _wire2api_SmtcInternal,
      constMeta: kSmtcNewConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcNewConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_new",
        argNames: [],
      );

  Future<void> smtcUpdateConfig({required SmtcInternal internal, required SMTCConfig config, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = _platform.api2wire_box_autoadd_smtc_config(config);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_config(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdateConfigConstMeta,
      argValues: [
        internal,
        config
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateConfigConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_config",
        argNames: [
          "internal",
          "config"
        ],
      );

  Future<void> smtcUpdateMetadata({required SmtcInternal internal, required MusicMetadata metadata, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = _platform.api2wire_box_autoadd_music_metadata(metadata);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_metadata(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdateMetadataConstMeta,
      argValues: [
        internal,
        metadata
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateMetadataConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_metadata",
        argNames: [
          "internal",
          "metadata"
        ],
      );

  Future<void> smtcUpdateTimeline({required SmtcInternal internal, required PlaybackTimeline timeline, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = _platform.api2wire_box_autoadd_playback_timeline(timeline);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_timeline(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdateTimelineConstMeta,
      argValues: [
        internal,
        timeline
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateTimelineConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_timeline",
        argNames: [
          "internal",
          "timeline"
        ],
      );

  Future<void> smtcUpdatePlaybackStatus({required SmtcInternal internal, required PlaybackStatus status, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = api2wire_playback_status(status);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_playback_status(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdatePlaybackStatusConstMeta,
      argValues: [
        internal,
        status
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdatePlaybackStatusConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_playback_status",
        argNames: [
          "internal",
          "status"
        ],
      );

  Future<void> smtcUpdateShuffle({required SmtcInternal internal, required bool shuffle, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = shuffle;
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_shuffle(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdateShuffleConstMeta,
      argValues: [
        internal,
        shuffle
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateShuffleConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_shuffle",
        argNames: [
          "internal",
          "shuffle"
        ],
      );

  Future<void> smtcUpdateRepeatMode({required SmtcInternal internal, required String repeatMode, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    var arg1 = _platform.api2wire_String(repeatMode);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_update_repeat_mode(port_, arg0, arg1),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcUpdateRepeatModeConstMeta,
      argValues: [
        internal,
        repeatMode
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcUpdateRepeatModeConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_update_repeat_mode",
        argNames: [
          "internal",
          "repeatMode"
        ],
      );

  Future<void> smtcDisableSmtc({required SmtcInternal internal, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_disable_smtc(port_, arg0),
      parseSuccessData: _wire2api_unit,
      constMeta: kSmtcDisableSmtcConstMeta,
      argValues: [
        internal
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcDisableSmtcConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_disable_smtc",
        argNames: [
          "internal"
        ],
      );

  Stream<String> smtcButtonPressEvent({required SmtcInternal internal, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_button_press_event(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kSmtcButtonPressEventConstMeta,
      argValues: [
        internal
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcButtonPressEventConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_button_press_event",
        argNames: [
          "internal"
        ],
      );

  Stream<int> smtcPositionChangeRequestEvent({required SmtcInternal internal, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_position_change_request_event(port_, arg0),
      parseSuccessData: _wire2api_i64,
      constMeta: kSmtcPositionChangeRequestEventConstMeta,
      argValues: [
        internal
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcPositionChangeRequestEventConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_position_change_request_event",
        argNames: [
          "internal"
        ],
      );

  Stream<bool> smtcShuffleRequestEvent({required SmtcInternal internal, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_shuffle_request_event(port_, arg0),
      parseSuccessData: _wire2api_bool,
      constMeta: kSmtcShuffleRequestEventConstMeta,
      argValues: [
        internal
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcShuffleRequestEventConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_shuffle_request_event",
        argNames: [
          "internal"
        ],
      );

  Stream<String> smtcRepeatModeRequestEvent({required SmtcInternal internal, dynamic hint}) {
    var arg0 = _platform.api2wire_SmtcInternal(internal);
    return _platform.executeStream(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_smtc_repeat_mode_request_event(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kSmtcRepeatModeRequestEventConstMeta,
      argValues: [
        internal
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSmtcRepeatModeRequestEventConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "smtc_repeat_mode_request_event",
        argNames: [
          "internal"
        ],
      );

  DropFnType get dropOpaqueSmtcInternal => _platform.inner.drop_opaque_SmtcInternal;
  ShareFnType get shareOpaqueSmtcInternal => _platform.inner.share_opaque_SmtcInternal;
  OpaqueTypeFinalizer get SmtcInternalFinalizer => _platform.SmtcInternalFinalizer;

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  SmtcInternal _wire2api_SmtcInternal(dynamic raw) {
    return SmtcInternal.fromRaw(raw[0], raw[1], this);
  }

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  bool _wire2api_bool(dynamic raw) {
    return raw as bool;
  }

  int _wire2api_i64(dynamic raw) {
    return castInt(raw);
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }

  void _wire2api_unit(dynamic raw) {
    return;
  }
}

// Section: api2wire

@protected
bool api2wire_bool(bool raw) {
  return raw;
}

@protected
int api2wire_i32(int raw) {
  return raw;
}

@protected
int api2wire_playback_status(PlaybackStatus raw) {
  return api2wire_i32(raw.index);
}

@protected
int api2wire_u32(int raw) {
  return raw;
}

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer
